
export const FETCTH_PHOTOS_URL_PENDING = "FETCTH_PHOTOS_URL_PENDING" 
export const FETCTH_PHOTOS_URL_SUCCESS = "FETCTH_PHOTOS_URL_SUCESS" 
export const FETCTH_PHOTOS_URL_ERROR = "FETCTH_PHOTOS_URL_ERROR" 
export const CLEAN_STATE = "CLEAN_STATE"
export const FETCTH_PHOTOS_REPORTS = "FETCTH_PHOTOS_REPORTS"
export const FETCTH_PHOTOS_PORTRAITS = "FETCTH_PHOTOS_PORTRIATS"
export const FETCTH_PHOTOS_LANDSCAPE = "FETCTH_PHOTOS_LANDSCAPE"